version: 0.2
env:
  variables:
    GOOS: "linux"
    GOARCH: "amd64"
phases:
  build:
    commands:
      - chmod +x go-lambda-1/build.sh
      - go-lambda-1/build.sh
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket test --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
