version: 0.2
env:
  variables:
    GOOS: "linux"
    GOARCH: "amd64"
phases:
  build:
    commands:
      - go-lambda-1/build.sh
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
